# SteamOKAutomaticScript Configuration

# Paths Configuration
paths:
  # Excel file paths
  results_excel: "result/games.xlsx"
  test_games_excel: "result/games.xlsx"
  
  # Screenshot directory
  screenshots_dir: "screenshots"
  
  # Logs configuration
  logs_dir: "logs"
  
  # Steam directory paths
  steam_apps_base: "E:/Steam/steamapps"  # Base SteamApps directory
  
# Image Detection
image_detector:
  retry_interval: 2
  max_retries: 3
  default_confidence: 0.9
  wait_after_click: 1

# Timing Configuration
timing:
  typing_delay: 0.5
  app_launch_delay: 1
  window_activate_delay: 1
  click_delay: 0.5

  installation_timeout: 10800  # 2 hours (7200 seconds) maximum for game installation
  # Delays in seconds
  window_activation_delay: 0.5
  search_input_delay: 0.5
  search_result_delay: 2.0
  installation_check_interval: 10  # How often to check if installation is complete
  game_launch_timeout: 300  # 5 minutes maximum for game launch
  game_close_timeout: 60  # 1 minute maximum for game closing
  retry_delay: 5  # How long to wait between retries

# Game Processing
game_controller:
  playable_button_image: "png/steam_playable_button.png"
  playable_download_icon_image: "png/steam_playable_download_icon.png"
  steamok_not_save_image: "png/steamok_not_save.png"
  steamok_save_image: "png/steamok_save.png"
  steamok_not_use_save_image: "png/steamok_not_use_save.png"
  steamok_search_box_image: "png/steamok_search_box.png"
  steamok_game_list_image: "png/steamok_game_list.png"
  steamok_play_button_image: "png/steamok_play_button.png"
  steamok_confirm_play_button_image: "png/steamok_confirm_play_button.png"
  steam_install_button_image: "png/steam_install_button.png"
  steam_install_button_image2: "png/steam_install_button2.png"
  steam_reinstall_button_image: "png/steam_reinstall_button.png"
  steam_reinstall_button_image2: "png/steam_reinstall_button2.png"
  steam_accept_button_image: "png/steam_accept_button.png"
# DLL Injection
dll_injection:
  enabled: true  # Whether to perform DLL injection
  timeout: 300  # Maximum time to wait for DLL injection in seconds
  
  # DLL Injection specific paths
  paths:
    # Path to base log directory for injection logs
    log_directory: "C:/Dumper-7/log"
    # DLL injector executable path
    dll_injector_path: "E:/DLL Injector.lnk"

  # Image paths for DLL injection process
  images:
    playable_button_image: "png/steam_playable_button.png"
    start_game_image: "png/inject_start_game.png"
    launch_options_start_game_image: "png/inject_launch_options_start_game.png"
    comfirm_vr_image: "png/inject_comfirm_vr.png"
    network_allow_image: "png/inject_network_allow.png"
    still_play_game_image: "png/inject_still_play_game.png"
  
  # Process detection
  process_detection:
    # System process keywords to filter out when finding game processes
    system_process_keywords:
      - "svchost"
      - "explorer"
      - "dllhost"
      - "runtimebroker"
      - "steamwebhelper"
      - "taskmgr"
      - "python"
      - "cmd"
      - "conhost"
      - "searchapp"
      - "rundll32"
  
  # Sleep timings for DLL injection process
  sleep_timings:
    window_activate: 0.3       # Time to wait after window activation
    click_delay: 0.5           # Time to wait after clicking
    dll_injector_start: 5      # Time to wait for DLL Injector to start
    process_check: 2           # Time between process checks
    game_launch: 15            # Time to wait for game to launch
    minimize_wait: 1           # Time to wait after minimizing windows
    retry_interval: 2          # Time between retries for various operations
    keyboard_delay: 0.1        # Time between keyboard actions
    injection_check: 2         # Time between injection status checks
    window_close: 1            # Time to wait after closing windows
    injection_max_wait: 240    # Maximum time to wait for injection (4 minutes)
  
  # Retry counts for injection steps
  retry_counts:
    launch_options: 5          # Max retries for detecting Steam launch options
    firewall_permission: 5     # Max retries for detecting firewall permissions
    cloud_save: 5              # Max retries for detecting cloud save dialog

